name: Publish

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: 19
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Publish to GitHub Packages
      run: gradle publish
      env:
        GH_USERNAME: ${{ github.actor }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
